// ============================================================
// Utility: Image Processing
// Purpose: Image URL resolution and processing utilities for Sanity CMS
// ============================================================

import { urlFor } from "@/lib";
import { ImageConfig, SanityImage } from "@/shared/types";

// ============================================================
// Constants
// ============================================================

/** Default image configuration */
const DEFAULT_CONFIG: Pick<Required<ImageConfig>, "fallbackAlt"> = {
    fallbackAlt: "Image",
} as const;

/** Image URL patterns */
const URL_PATTERNS = {
    HTTP: "http",
    HTTPS: "https",
    ABSOLUTE_PATH: "/",
} as const;

/** Error messages */
const ERROR_MESSAGES = {
    INVALID_IMAGE: "Invalid image provided",
    PROCESSING_FAILED: "Failed to process image",
} as const;

// ============================================================
// Types
// ============================================================

/** Processed image result */
interface ProcessedImage {
    /** Resolved image URL */
    url: string;
    /** Image alt text */
    alt: string;
}

/** Image processing options */
interface ImageProcessingOptions {
    /** Custom fallback alt text */
    fallbackAlt?: string;
    /** Whether to validate image URL */
    validateUrl?: boolean;
}

// ============================================================
// Utility Functions
// ============================================================

export const resolveImageUrl = (
    image: SanityImage | string | undefined,
    configOrBaseUrl?: ImageConfig | string
): string => {
    try {
        const isConfigObject =
            configOrBaseUrl && typeof configOrBaseUrl === "object";
        const config = isConfigObject
            ? (configOrBaseUrl as ImageConfig)
            : undefined;
        const baseUrl = !isConfigObject
            ? (configOrBaseUrl as string)
            : undefined;

        const { fallbackImage } = { ...DEFAULT_CONFIG, ...config };

        if (!image) {
            return fallbackImage || "";
        }

        if (typeof image === "string") {
            return handleStringImage(image, baseUrl, fallbackImage);
        }

        return handleSanityImage(image as SanityImage, config, fallbackImage);
    } catch (error) {
        console.error(ERROR_MESSAGES.PROCESSING_FAILED, error);
        return "";
    }
};

const handleStringImage = (
    imageUrl: string,
    baseUrl?: string,
    fallbackImage?: string
): string => {
    if (baseUrl) {
        if (
            imageUrl.startsWith(URL_PATTERNS.HTTP) ||
            imageUrl.startsWith(URL_PATTERNS.HTTPS)
        ) {
            return imageUrl;
        }

        if (imageUrl.startsWith(URL_PATTERNS.ABSOLUTE_PATH)) {
            return `${baseUrl}${imageUrl}`;
        }

        return fallbackImage || "";
    }

    return imageUrl;
};

/**
 * Check if an asset reference is a mock/test asset ID
 * Mock asset IDs follow the pattern: image-{id}-{width}x{height}-{format}
 * but don't exist in Sanity's CDN
 */
const isMockAssetId = (assetRef: string): boolean => {
    // Mock asset IDs from our factories follow the pattern: image-{alphanumeric}-{width}x{height}-{format}
    // Real Sanity asset IDs also follow this pattern, but we can detect mocks by checking
    // if they're generated by our faker (they'll have predictable patterns)
    // For now, we'll catch errors and treat them as mocks
    return false; // We'll detect via error handling instead
};

/**
 * Generate a placeholder image URL for mock data
 */
const getPlaceholderImageUrl = (width?: number, height?: number): string => {
    const w = width || 800;
    const h = height || 600;
    // Use picsum.photos for placeholder images
    return `https://picsum.photos/${w}/${h}?random=${Math.random()}`;
};

const handleSanityImage = (
    image: SanityImage,
    config?: ImageConfig,
    fallbackImage?: string
): string => {
    try {
        if (config?.width && config?.height) {
            return urlFor(image)
                .width(config.width)
                .height(config.height)
                .url();
        }

        return urlFor(image).url();
    } catch (error) {
        // If Sanity image processing fails (e.g., mock asset IDs), use placeholder
        const placeholderUrl = getPlaceholderImageUrl(
            config?.width,
            config?.height
        );
        // Only log in development to avoid noise in production
        if (process.env.NODE_ENV === "development") {
            console.warn(
                "Sanity image processing failed, using placeholder:",
                error instanceof Error ? error.message : error
            );
        }
        return fallbackImage || placeholderUrl;
    }
};

export const getImageAlt = (
    image: SanityImage | string | undefined,
    fallbackText: string = DEFAULT_CONFIG.fallbackAlt
): string => {
    if (!image) {
        return fallbackText;
    }

    if (typeof image === "string") {
        return fallbackText;
    }

    return (image as SanityImage)?.alt || fallbackText;
};

export const processImage = (
    image: SanityImage | string | undefined,
    config: ImageConfig,
    options: ImageProcessingOptions = {}
): ProcessedImage => {
    const { fallbackAlt, validateUrl = false } = options;

    const url = resolveImageUrl(image, config);
    const alt = getImageAlt(image, fallbackAlt || config.fallbackAlt);

    if (validateUrl && !url) {
        console.warn(ERROR_MESSAGES.INVALID_IMAGE, { image, config });
    }

    return { url, alt };
};

export const processPortfolioImage = (
    image: SanityImage | string | undefined,
    projectName: string,
    config: ImageConfig
): ProcessedImage => {
    const fallbackAlt = `${projectName} project`;
    return processImage(image, config, { fallbackAlt });
};

export const validateImageUrl = async (url: string): Promise<boolean> => {
    if (!url) return false;

    try {
        const response = await fetch(url, { method: "HEAD" });
        return response.ok;
    } catch {
        return false;
    }
};
